image: docker:19

variables:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  REGISTRY_NAMESPACE: fattigerlee
  REGISTRY_USER: 505179140@qq.com
  REGISTRY_PASSWORD: C317t#VrjAb*r%uv
  APP1: test_cicd
  APP2: test_demo

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
  - chmod +x ./script/*.sh

after_script:
  - docker container prune -f
  - docker image prune -f

stages:
  - build
  - deploy

# 构建测试版本

# 构建正式版本
build-master:
  stage: build
  tags:
    - develop
  only:
    - master
  script:
    - ./script/build.sh master $REGISTRY $REGISTRY_NAMESPACE $APP1
    - ./script/build.sh master $REGISTRY $REGISTRY_NAMESPACE $APP2

# 部署测试版本
deploy-develop:
  stage: deploy
  when: on_success
  tags:
    - develop
  only:
    - master
  script:
    - ./script/deploy.sh master $REGISTRY/$REGISTRY_NAMESPACE/$APP1 0.0.0.0 80
    - ./script/deploy.sh master $REGISTRY/$REGISTRY_NAMESPACE/$APP2 0.0.0.0 81

# 部署正式版本(手动执行)
deploy-master:
  stage: deploy
  when: manual
  tags:
    - develop
  only:
    - master
  script:
    - ./script/deploy.sh master $REGISTRY/$REGISTRY_NAMESPACE/$APP1 0.0.0.0 80
    - ./script/deploy.sh master $REGISTRY/$REGISTRY_NAMESPACE/$APP2 0.0.0.0 81